/* ============ 雅思高频词库（背单词功能内置数据） ============
 * 三档单词 + 高频词组，格式：[词, 音标, 释义] / 词组：[词组, 释义]
 * 扩充词库：往对应数组里加一行即可，vid 自动生成（w:单词 / p:词组）。
 * 音标为英式 IPA；释义以雅思常考义项优先。
 */

const T1 = [ // ---------- 基础高频 ----------
  ['abandon', '/əˈbændən/', 'v. 放弃；抛弃'],
  ['ability', '/əˈbɪləti/', 'n. 能力；才能'],
  ['absorb', '/əbˈzɔːb/', 'v. 吸收；使专心'],
  ['abstract', '/ˈæbstrækt/', 'adj. 抽象的 n. 摘要'],
  ['abundant', '/əˈbʌndənt/', 'adj. 丰富的；充裕的'],
  ['academic', '/ˌækəˈdemɪk/', 'adj. 学业的；学术的'],
  ['access', '/ˈækses/', 'n. 通道；使用权 v. 访问'],
  ['accompany', '/əˈkʌmpəni/', 'v. 陪伴；伴随'],
  ['accomplish', '/əˈkʌmplɪʃ/', 'v. 完成；实现'],
  ['account', '/əˈkaʊnt/', 'n. 账户；描述 v. 解释'],
  ['accurate', '/ˈækjərət/', 'adj. 准确的；精确的'],
  ['achieve', '/əˈtʃiːv/', 'v. 实现；达到'],
  ['acquire', '/əˈkwaɪə/', 'v. 获得；习得'],
  ['adapt', '/əˈdæpt/', 'v. 适应；改编'],
  ['adequate', '/ˈædɪkwət/', 'adj. 足够的；合格的'],
  ['adjust', '/əˈdʒʌst/', 'v. 调整；适应'],
  ['admire', '/ədˈmaɪə/', 'v. 钦佩；欣赏'],
  ['adopt', '/əˈdɒpt/', 'v. 采纳；收养'],
  ['advantage', '/ədˈvɑːntɪdʒ/', 'n. 优势；好处'],
  ['advocate', '/ˈædvəkeɪt/', 'v. 提倡 n. 拥护者'],
  ['affect', '/əˈfekt/', 'v. 影响'],
  ['afford', '/əˈfɔːd/', 'v. 买得起；承担得起'],
  ['aggressive', '/əˈgresɪv/', 'adj. 好斗的；进取的'],
  ['agriculture', '/ˈæɡrɪkʌltʃə/', 'n. 农业'],
  ['alternative', '/ɔːlˈtɜːnətɪv/', 'n. 替代方案 adj. 可替代的'],
  ['ambitious', '/æmˈbɪʃəs/', 'adj. 有雄心的'],
  ['analyze', '/ˈænəlaɪz/', 'v. 分析'],
  ['announce', '/əˈnaʊns/', 'v. 宣布'],
  ['annual', '/ˈænjuəl/', 'adj. 每年的'],
  ['apparent', '/əˈpærənt/', 'adj. 明显的；表面上的'],
  ['appeal', '/əˈpiːl/', 'n. 吸引力 v. 呼吁'],
  ['apply', '/əˈplaɪ/', 'v. 申请；应用'],
  ['appreciate', '/əˈpriːʃieɪt/', 'v. 感激；欣赏'],
  ['approach', '/əˈprəʊtʃ/', 'n. 方法 v. 接近'],
  ['appropriate', '/əˈprəʊpriət/', 'adj. 恰当的'],
  ['approve', '/əˈpruːv/', 'v. 批准；赞成'],
  ['argue', '/ˈɑːɡjuː/', 'v. 争论；主张'],
  ['arise', '/əˈraɪz/', 'v. 出现；产生'],
  ['arrange', '/əˈreɪndʒ/', 'v. 安排；整理'],
  ['artificial', '/ˌɑːtɪˈfɪʃl/', 'adj. 人造的；人工的'],
  ['assess', '/əˈses/', 'v. 评估；评定'],
  ['assign', '/əˈsaɪn/', 'v. 分配；指派'],
  ['assist', '/əˈsɪst/', 'v. 协助'],
  ['assume', '/əˈsjuːm/', 'v. 假定；承担'],
  ['atmosphere', '/ˈætməsfɪə/', 'n. 大气；气氛'],
  ['attach', '/əˈtætʃ/', 'v. 系上；附加'],
  ['attempt', '/əˈtempt/', 'n./v. 尝试；努力'],
  ['attend', '/əˈtend/', 'v. 出席；照料'],
  ['attitude', '/ˈætɪtjuːd/', 'n. 态度；看法'],
  ['attract', '/əˈtrækt/', 'v. 吸引'],
  ['available', '/əˈveɪləbl/', 'adj. 可获得的；有空的'],
  ['average', '/ˈævərɪdʒ/', 'adj. 平均的 n. 平均数'],
  ['avoid', '/əˈvɔɪd/', 'v. 避免'],
  ['aware', '/əˈweə/', 'adj. 意识到的'],
  ['balance', '/ˈbæləns/', 'n. 平衡 v. 使平衡'],
  ['barrier', '/ˈbæriə/', 'n. 障碍；屏障'],
  ['benefit', '/ˈbenɪfɪt/', 'n. 好处 v. 受益'],
  ['calculate', '/ˈkælkjuleɪt/', 'v. 计算；预测'],
  ['campaign', '/kæmˈpeɪn/', 'n. 运动；活动'],
  ['candidate', '/ˈkændɪdət/', 'n. 候选人；考生'],
  ['capacity', '/kəˈpæsəti/', 'n. 容量；能力'],
  ['category', '/ˈkætəɡəri/', 'n. 类别'],
  ['challenge', '/ˈtʃælɪndʒ/', 'n. 挑战 v. 质疑'],
  ['characteristic', '/ˌkærəktəˈrɪstɪk/', 'n. 特征 adj. 典型的'],
  ['circumstance', '/ˈsɜːkəmstəns/', 'n. 情况；环境'],
  ['collaborate', '/kəˈlæbəreɪt/', 'v. 合作'],
  ['combine', '/kəmˈbaɪn/', 'v. 结合；联合'],
  ['comment', '/ˈkɒment/', 'n. 评论 v. 发表意见'],
  ['communicate', '/kəˈmjuːnɪkeɪt/', 'v. 交流；传达'],
  ['community', '/kəˈmjuːnəti/', 'n. 社区；群体'],
  ['compare', '/kəmˈpeə/', 'v. 比较'],
  ['compete', '/kəmˈpiːt/', 'v. 竞争'],
  ['concentrate', '/ˈkɒnsntreɪt/', 'v. 集中；专心'],
  ['concept', '/ˈkɒnsept/', 'n. 概念；观念'],
  ['concern', '/kənˈsɜːn/', 'n. 担忧 v. 涉及'],
  ['conclude', '/kənˈkluːd/', 'v. 得出结论；结束'],
  ['conduct', '/kənˈdʌkt/', 'v. 实施；指挥'],
  ['confident', '/ˈkɒnfɪdənt/', 'adj. 自信的'],
  ['confirm', '/kənˈfɜːm/', 'v. 确认；证实'],
  ['conflict', '/ˈkɒnflɪkt/', 'n. 冲突；矛盾'],
  ['confuse', '/kənˈfjuːz/', 'v. 使困惑'],
  ['conscious', '/ˈkɒnʃəs/', 'adj. 有意识的；刻意的'],
  ['consequence', '/ˈkɒnsɪkwəns/', 'n. 后果；结果'],
  ['conservative', '/kənˈsɜːvətɪv/', 'adj. 保守的'],
  ['considerable', '/kənˈsɪdərəbl/', 'adj. 相当大的'],
  ['consist', '/kənˈsɪst/', 'v. 由…组成'],
  ['constant', '/ˈkɒnstənt/', 'adj. 持续的；不变的'],
  ['construct', '/kənˈstrʌkt/', 'v. 建造；构建'],
  ['consult', '/kənˈsʌlt/', 'v. 咨询；商量'],
  ['consume', '/kənˈsjuːm/', 'v. 消耗；消费'],
  ['contain', '/kənˈteɪn/', 'v. 包含；容纳'],
  ['contemporary', '/kənˈtemprəri/', 'adj. 当代的 n. 同代人'],
  ['contract', '/ˈkɒntrækt/', 'n. 合同 v. 收缩'],
  ['contrast', '/ˈkɒntrɑːst/', 'n. 对比 v. 形成对比'],
  ['contribute', '/kənˈtrɪbjuːt/', 'v. 贡献；导致'],
  ['convenient', '/kənˈviːniənt/', 'adj. 方便的'],
  ['convince', '/kənˈvɪns/', 'v. 说服；使确信'],
  ['cooperate', '/kəʊˈɒpəreɪt/', 'v. 合作'],
  ['coordinate', '/kəʊˈɔːdɪneɪt/', 'v. 协调'],
  ['correct', '/kəˈrekt/', 'adj. 正确的 v. 纠正'],
  ['correspond', '/ˌkɒrɪˈspɒnd/', 'v. 符合；通信'],
  ['crisis', '/ˈkraɪsɪs/', 'n. 危机'],
  ['critical', '/ˈkrɪtɪkl/', 'adj. 批评的；关键的'],
  ['cultivate', '/ˈkʌltɪveɪt/', 'v. 培养；耕种'],
  ['curious', '/ˈkjʊəriəs/', 'adj. 好奇的'],
  ['currency', '/ˈkʌrənsi/', 'n. 货币'],
  ['current', '/ˈkʌrənt/', 'adj. 当前的 n. 水流/电流'],
  ['debate', '/dɪˈbeɪt/', 'n./v. 辩论'],
  ['decade', '/ˈdekeɪd/', 'n. 十年'],
  ['decline', '/dɪˈklaɪn/', 'v. 下降；婉拒'],
  ['dedicate', '/ˈdedɪkeɪt/', 'v. 奉献；致力于'],
  ['define', '/dɪˈfaɪn/', 'v. 定义；界定'],
  ['demand', '/dɪˈmɑːnd/', 'n. 需求 v. 要求'],
  ['demonstrate', '/ˈdemənstreɪt/', 'v. 证明；演示'],
  ['deny', '/dɪˈnaɪ/', 'v. 否认'],
  ['depend', '/dɪˈpend/', 'v. 依赖；取决于'],
  ['depict', '/dɪˈpɪkt/', 'v. 描绘；描述'],
  ['derive', '/dɪˈraɪv/', 'v. 源于；获得'],
  ['despite', '/dɪˈspaɪt/', 'prep. 尽管'],
  ['destroy', '/dɪˈstrɔɪ/', 'v. 破坏'],
  ['detect', '/dɪˈtekt/', 'v. 察觉；探测'],
  ['determine', '/dɪˈtɜːmɪn/', 'v. 决定；确定'],
  ['device', '/dɪˈvaɪs/', 'n. 装置；设备'],
  ['devote', '/dɪˈvəʊt/', 'v. 奉献；投入'],
  ['digital', '/ˈdɪdʒɪtl/', 'adj. 数字的'],
  ['dimension', '/daɪˈmenʃn/', 'n. 维度；尺寸'],
  ['discipline', '/ˈdɪsəplɪn/', 'n. 纪律；学科'],
  ['display', '/dɪˈspleɪ/', 'v. 展示 n. 显示器'],
  ['distinguish', '/dɪˈstɪŋɡwɪʃ/', 'v. 区分；辨别'],
  ['distribute', '/dɪˈstrɪbjuːt/', 'v. 分配；分布'],
  ['diverse', '/daɪˈvɜːs/', 'adj. 多样的'],
  ['domestic', '/dəˈmestɪk/', 'adj. 国内的；家庭的'],
  ['dominate', '/ˈdɒmɪneɪt/', 'v. 支配；主导'],
  ['dramatic', '/drəˈmætɪk/', 'adj. 戏剧性的；急剧的'],
  ['economy', '/ɪˈkɒnəmi/', 'n. 经济'],
  ['educate', '/ˈedʒukeɪt/', 'v. 教育'],
  ['efficient', '/ɪˈfɪʃnt/', 'adj. 高效的'],
  ['eliminate', '/ɪˈlɪmɪneɪt/', 'v. 消除；淘汰'],
  ['emerge', '/iˈmɜːdʒ/', 'v. 出现；浮现'],
  ['emotion', '/ɪˈməʊʃn/', 'n. 情感'],
  ['emphasize', '/ˈemfəsaɪz/', 'v. 强调'],
  ['employ', '/ɪmˈplɔɪ/', 'v. 雇佣；使用'],
  ['enable', '/ɪˈneɪbl/', 'v. 使能够'],
  ['encourage', '/ɪnˈkʌrɪdʒ/', 'v. 鼓励'],
  ['engage', '/ɪnˈɡeɪdʒ/', 'v. 从事；吸引'],
  ['enhance', '/ɪnˈhɑːns/', 'v. 提高；增强'],
  ['enormous', '/ɪˈnɔːməs/', 'adj. 巨大的'],
  ['ensure', '/ɪnˈʃʊə/', 'v. 确保'],
  ['environment', '/ɪnˈvaɪrənmənt/', 'n. 环境'],
  ['establish', '/ɪˈstæblɪʃ/', 'v. 建立；确立'],
  ['estimate', '/ˈestɪmət/', 'v. 估计 n. 估算'],
  ['evaluate', '/ɪˈvæljueɪt/', 'v. 评估'],
  ['evidence', '/ˈevɪdəns/', 'n. 证据'],
  ['exaggerate', '/ɪɡˈzædʒəreɪt/', 'v. 夸大'],
  ['exceed', '/ɪkˈsiːd/', 'v. 超过'],
  ['exchange', '/ɪksˈtʃeɪndʒ/', 'v./n. 交换；兑换'],
  ['expand', '/ɪkˈspænd/', 'v. 扩大'],
  ['expect', '/ɪkˈspekt/', 'v. 预期；期待'],
  ['experiment', '/ɪkˈsperɪmənt/', 'n. 实验'],
  ['expert', '/ˈekspɜːt/', 'n. 专家'],
  ['explore', '/ɪkˈsplɔː/', 'v. 探索'],
  ['expose', '/ɪkˈspəʊz/', 'v. 暴露；使接触'],
  ['extend', '/ɪkˈstend/', 'v. 延伸；扩展'],
  ['extent', '/ɪkˈstent/', 'n. 程度；范围'],
  ['facility', '/fəˈsɪləti/', 'n. 设施'],
  ['factor', '/ˈfæktə/', 'n. 因素'],
  ['feature', '/ˈfiːtʃə/', 'n. 特征 v. 以…为特色'],
  ['finance', '/ˈfaɪnæns/', 'n. 财政 v. 资助'],
  ['flexible', '/ˈfleksəbl/', 'adj. 灵活的'],
  ['focus', '/ˈfəʊkəs/', 'v. 集中 n. 焦点'],
  ['formulate', '/ˈfɔːmjuleɪt/', 'v. 制定；系统阐述'],
  ['foundation', '/faʊnˈdeɪʃn/', 'n. 基础；基金会'],
  ['frequent', '/ˈfriːkwənt/', 'adj. 频繁的'],
  ['function', '/ˈfʌŋkʃn/', 'n. 功能 v. 运作'],
  ['fund', '/fʌnd/', 'n. 基金 v. 资助'],
  ['fundamental', '/ˌfʌndəˈmentl/', 'adj. 基本的；根本的'],
  ['generate', '/ˈdʒenəreɪt/', 'v. 产生；引起'],
];

const T2 = [ // ---------- 核心高频 ----------
  ['hypothesis', '/haɪˈpɒθəsɪs/', 'n. 假设；假说'],
  ['implement', '/ˈɪmplɪment/', 'v. 实施；执行'],
  ['imply', '/ɪmˈplaɪ/', 'v. 暗示；意味'],
  ['incentive', '/ɪnˈsentɪv/', 'n. 激励；动机'],
  ['incorporate', '/ɪnˈkɔːpəreɪt/', 'v. 包含；合并'],
  ['indicate', '/ˈɪndɪkeɪt/', 'v. 表明；指出'],
  ['individual', '/ˌɪndɪˈvɪdʒuəl/', 'adj. 个人的 n. 个体'],
  ['inevitable', '/ɪnˈevɪtəbl/', 'adj. 不可避免的'],
  ['influence', '/ˈɪnfluəns/', 'n./v. 影响'],
  ['infrastructure', '/ˈɪnfrəstrʌktʃə/', 'n. 基础设施'],
  ['inherent', '/ɪnˈhɪərənt/', 'adj. 固有的；内在的'],
  ['initiate', '/ɪˈnɪʃieɪt/', 'v. 开始；发起'],
  ['insight', '/ˈɪnsaɪt/', 'n. 洞察；见解'],
  ['integrate', '/ˈɪntɪɡreɪt/', 'v. 整合；融合'],
  ['intellectual', '/ˌɪntəˈlektʃuəl/', 'adj. 智力的 n. 知识分子'],
  ['intense', '/ɪnˈtens/', 'adj. 强烈的；激烈的'],
  ['interact', '/ˌɪntərˈækt/', 'v. 互动；相互作用'],
  ['interpret', '/ɪnˈtɜːprɪt/', 'v. 解释；口译'],
  ['intervene', '/ˌɪntəˈviːn/', 'v. 干预；介入'],
  ['invest', '/ɪnˈvest/', 'v. 投资'],
  ['investigate', '/ɪnˈvestɪɡeɪt/', 'v. 调查；研究'],
  ['involve', '/ɪnˈvɒlv/', 'v. 涉及；包含'],
  ['isolate', '/ˈaɪsəleɪt/', 'v. 使隔离；孤立'],
  ['justify', '/ˈdʒʌstɪfaɪ/', 'v. 证明…正当'],
  ['legislation', '/ˌledʒɪsˈleɪʃn/', 'n. 立法；法规'],
  ['legitimate', '/lɪˈdʒɪtɪmət/', 'adj. 合法的；正当的'],
  ['maintain', '/meɪnˈteɪn/', 'v. 维持；保养'],
  ['manipulate', '/məˈnɪpjuleɪt/', 'v. 操纵；控制'],
  ['mature', '/məˈtʃʊə/', 'adj. 成熟的 v. 成熟'],
  ['mechanism', '/ˈmekənɪzəm/', 'n. 机制；机械装置'],
  ['mediate', '/ˈmiːdieɪt/', 'v. 调解；斡旋'],
  ['migrate', '/maɪˈɡreɪt/', 'v. 迁移；移居'],
  ['minimize', '/ˈmɪnɪmaɪz/', 'v. 最小化'],
  ['modify', '/ˈmɒdɪfaɪ/', 'v. 修改；调整'],
  ['monitor', '/ˈmɒnɪtə/', 'v. 监控 n. 显示器'],
  ['negotiate', '/nɪˈɡəʊʃieɪt/', 'v. 谈判；协商'],
  ['notion', '/ˈnəʊʃn/', 'n. 观念；概念'],
  ['objective', '/əbˈdʒektɪv/', 'n. 目标 adj. 客观的'],
  ['oblige', '/əˈblaɪdʒ/', 'v. 迫使；帮忙'],
  ['observe', '/əbˈzɜːv/', 'v. 观察；遵守'],
  ['obtain', '/əbˈteɪn/', 'v. 获得'],
  ['obvious', '/ˈɒbviəs/', 'adj. 明显的'],
  ['occupy', '/ˈɒkjupaɪ/', 'v. 占据；居住'],
  ['occur', '/əˈkɜː/', 'v. 发生；出现'],
  ['operate', '/ˈɒpəreɪt/', 'v. 运营；操作'],
  ['opportunity', '/ˌɒpəˈtjuːnəti/', 'n. 机会'],
  ['oppose', '/əˈpəʊz/', 'v. 反对'],
  ['optimistic', '/ˌɒptɪˈmɪstɪk/', 'adj. 乐观的'],
  ['outcome', '/ˈaʊtkʌm/', 'n. 结果'],
  ['overcome', '/ˌəʊvəˈkʌm/', 'v. 克服'],
  ['participate', '/pɑːˈtɪsɪpeɪt/', 'v. 参与'],
  ['perceive', '/pəˈsiːv/', 'v. 感知；认为'],
  ['permanent', '/ˈpɜːmənənt/', 'adj. 永久的'],
  ['persist', '/pəˈsɪst/', 'v. 坚持；持续'],
  ['perspective', '/pəˈspektɪv/', 'n. 观点；视角'],
  ['phenomenon', '/fəˈnɒmɪnən/', 'n. 现象'],
  ['philosophy', '/fəˈlɒsəfi/', 'n. 哲学；理念'],
  ['policy', '/ˈpɒləsi/', 'n. 政策；方针'],
  ['pollute', '/pəˈluːt/', 'v. 污染'],
  ['potential', '/pəˈtenʃl/', 'adj. 潜在的 n. 潜力'],
  ['practical', '/ˈpræktɪkl/', 'adj. 实际的；实用的'],
  ['precise', '/prɪˈsaɪs/', 'adj. 精确的'],
  ['predict', '/prɪˈdɪkt/', 'v. 预测'],
  ['primary', '/ˈpraɪməri/', 'adj. 首要的；初级的'],
  ['principle', '/ˈprɪnsəpl/', 'n. 原则；原理'],
  ['priority', '/praɪˈɒrəti/', 'n. 优先事项'],
  ['prohibit', '/prəˈhɪbɪt/', 'v. 禁止'],
  ['promote', '/prəˈməʊt/', 'v. 促进；晋升'],
  ['proportion', '/prəˈpɔːʃn/', 'n. 比例；部分'],
  ['prospect', '/ˈprɒspekt/', 'n. 前景；可能性'],
  ['psychology', '/saɪˈkɒlədʒi/', 'n. 心理学'],
  ['pursue', '/pəˈsjuː/', 'v. 追求；从事'],
  ['radical', '/ˈrædɪkl/', 'adj. 激进的；根本的'],
  ['random', '/ˈrændəm/', 'adj. 随机的'],
  ['range', '/reɪndʒ/', 'n. 范围 v. 变动'],
  ['rational', '/ˈræʃnəl/', 'adj. 理性的'],
  ['recover', '/rɪˈkʌvə/', 'v. 恢复；找回'],
  ['regulate', '/ˈreɡjuleɪt/', 'v. 调节；管理'],
  ['reject', '/rɪˈdʒekt/', 'v. 拒绝'],
  ['relevant', '/ˈreləvənt/', 'adj. 相关的'],
  ['reluctant', '/rɪˈlʌktənt/', 'adj. 不情愿的'],
  ['rely', '/rɪˈlaɪ/', 'v. 依赖'],
  ['remedy', '/ˈremədi/', 'n. 疗法；补救'],
  ['resource', '/rɪˈsɔːs/', 'n. 资源'],
  ['respond', '/rɪˈspɒnd/', 'v. 回应'],
  ['restore', '/rɪˈstɔː/', 'v. 恢复；修复'],
  ['restrict', '/rɪˈstrɪkt/', 'v. 限制'],
  ['retain', '/rɪˈteɪn/', 'v. 保留'],
  ['reveal', '/rɪˈviːl/', 'v. 揭示；显示'],
  ['revenue', '/ˈrevənjuː/', 'n. 收入；税收'],
  ['reverse', '/rɪˈvɜːs/', 'v. 逆转 adj. 相反的'],
  ['rigid', '/ˈrɪdʒɪd/', 'adj. 严格的；僵硬的'],
  ['rural', '/ˈrʊərəl/', 'adj. 农村的'],
  ['scarce', '/skeəs/', 'adj. 稀缺的'],
  ['schedule', '/ˈʃedjuːl/', 'n. 计划 v. 安排'],
  ['scheme', '/skiːm/', 'n. 计划；方案'],
  ['secure', '/sɪˈkjʊə/', 'adj. 安全的 v. 获得'],
  ['significant', '/sɪɡˈnɪfɪkənt/', 'adj. 重要的；显著的'],
  ['simulate', '/ˈsɪmjuleɪt/', 'v. 模拟'],
  ['source', '/sɔːs/', 'n. 来源；源头'],
  ['specific', '/spəˈsɪfɪk/', 'adj. 具体的；特定的'],
  ['speculate', '/ˈspekjuleɪt/', 'v. 推测'],
  ['standard', '/ˈstændəd/', 'n. 标准'],
  ['statistic', '/stəˈtɪstɪk/', 'n. 统计数据'],
  ['status', '/ˈsteɪtəs/', 'n. 地位；状态'],
  ['stimulate', '/ˈstɪmjuleɪt/', 'v. 刺激；激励'],
  ['strategy', '/ˈstrætədʒi/', 'n. 策略'],
  ['structure', '/ˈstrʌktʃə/', 'n. 结构 v. 构建'],
  ['submit', '/səbˈmɪt/', 'v. 提交；服从'],
  ['substantial', '/səbˈstænʃl/', 'adj. 大量的；实质的'],
  ['sufficient', '/səˈfɪʃnt/', 'adj. 足够的'],
  ['summarize', '/ˈsʌməraɪz/', 'v. 总结'],
  ['surplus', '/ˈsɜːpləs/', 'n. 过剩；盈余'],
  ['survive', '/səˈvaɪv/', 'v. 幸存'],
  ['suspect', '/səˈspekt/', 'v. 怀疑 n. 嫌疑人'],
  ['sustain', '/səˈsteɪn/', 'v. 维持；承受'],
  ['symbol', '/ˈsɪmbl/', 'n. 象征；符号'],
  ['tackle', '/ˈtækl/', 'v. 处理；解决'],
  ['temporary', '/ˈtemprəri/', 'adj. 暂时的'],
  ['tendency', '/ˈtendənsi/', 'n. 趋势；倾向'],
  ['theory', '/ˈθɪəri/', 'n. 理论'],
  ['transform', '/trænsˈfɔːm/', 'v. 转变'],
  ['transition', '/trænˈzɪʃn/', 'n. 过渡；转变'],
  ['transport', '/ˈtrænspɔːt/', 'n./v. 运输'],
  ['urban', '/ˈɜːbən/', 'adj. 城市的'],
  ['utilize', '/ˈjuːtəlaɪz/', 'v. 利用'],
  ['vary', '/ˈveəri/', 'v. 变化；不同'],
  ['vast', '/vɑːst/', 'adj. 广阔的；巨大的'],
  ['vehicle', '/ˈviːəkl/', 'n. 交通工具；媒介'],
  ['viable', '/ˈvaɪəbl/', 'adj. 可行的'],
  ['virtual', '/ˈvɜːtʃuəl/', 'adj. 虚拟的；几乎…的'],
  ['visual', '/ˈvɪʒuəl/', 'adj. 视觉的'],
  ['welfare', '/ˈwelfeə/', 'n. 福利'],
  ['whereas', '/weərˈæz/', 'conj. 然而'],
];

const T3 = [ // ---------- 进阶词汇 ----------
  ['abrupt', '/əˈbrʌpt/', 'adj. 突然的；鲁莽的'],
  ['ambiguous', '/æmˈbɪɡjuəs/', 'adj. 模棱两可的'],
  ['analogous', '/əˈnæləɡəs/', 'adj. 类似的'],
  ['anticipate', '/ænˈtɪsɪpeɪt/', 'v. 预期；先于…行动'],
  ['arbitrary', '/ˈɑːbɪtrəri/', 'adj. 任意的；武断的'],
  ['coherent', '/kəʊˈhɪərənt/', 'adj. 连贯的；一致的'],
  ['compel', '/kəmˈpel/', 'v. 强迫'],
  ['compile', '/kəmˈpaɪl/', 'v. 汇编；编制'],
  ['comprehensive', '/ˌkɒmprɪˈhensɪv/', 'adj. 全面的'],
  ['comprise', '/kəmˈpraɪz/', 'v. 包含；组成'],
  ['concise', '/kənˈsaɪs/', 'adj. 简洁的'],
  ['contemplate', '/ˈkɒntəmpleɪt/', 'v. 沉思；考虑'],
  ['contradict', '/ˌkɒntrəˈdɪkt/', 'v. 反驳；与…矛盾'],
  ['converge', '/kənˈvɜːdʒ/', 'v. 汇聚；聚集'],
  ['credible', '/ˈkredəbl/', 'adj. 可信的'],
  ['delegate', '/ˈdelɪɡət/', 'v. 委派 n. 代表'],
  ['deliberate', '/dɪˈlɪbərət/', 'adj. 故意的 v. 深思熟虑'],
  ['dense', '/dens/', 'adj. 密集的；浓密的'],
  ['discourse', '/ˈdɪskɔːs/', 'n. 论述；话语'],
  ['eloquent', '/ˈeləkwənt/', 'adj. 雄辩的'],
  ['empirical', '/ɪmˈpɪrɪkl/', 'adj. 实证的；经验的'],
  ['endeavor', '/ɪnˈdevə/', 'n./v. 努力；尝试'],
  ['erratic', '/ɪˈrætɪk/', 'adj. 反复无常的'],
  ['exemplary', '/ɪɡˈzempləri/', 'adj. 典范的'],
  ['excerpt', '/ˈekszɜːpt/', 'n. 摘录'],
  ['facilitate', '/fəˈsɪlɪteɪt/', 'v. 促进；使便利'],
  ['feasible', '/ˈfiːzəbl/', 'adj. 可行的'],
  ['fluctuate', '/ˈflʌktʃueɪt/', 'v. 波动'],
  ['formidable', '/ˈfɔːmɪdəbl/', 'adj. 可怕的；强大的'],
  ['hinder', '/ˈhɪndə/', 'v. 阻碍'],
  ['impeccable', '/ɪmˈpekəbl/', 'adj. 无懈可击的'],
  ['imperative', '/ɪmˈperətɪv/', 'adj. 至关重要的'],
  ['implicit', '/ɪmˈplɪsɪt/', 'adj. 含蓄的；隐含的'],
  ['innate', '/ɪˈneɪt/', 'adj. 天生的'],
  ['intricate', '/ˈɪntrɪkət/', 'adj. 错综复杂的'],
  ['intrinsic', '/ɪnˈtrɪnsɪk/', 'adj. 内在的；固有的'],
  ['meticulous', '/məˈtɪkjələs/', 'adj. 一丝不苟的'],
  ['negligible', '/ˈneɡlɪdʒəbl/', 'adj. 微不足道的'],
  ['notorious', '/nəʊˈtɔːriəs/', 'adj. 臭名昭著的'],
  ['obsolete', '/ˈɒbsəliːt/', 'adj. 过时的'],
  ['paradox', '/ˈpærədɒks/', 'n. 悖论；矛盾'],
  ['pertinent', '/ˈpɜːtɪnənt/', 'adj. 相关的；切题的'],
  ['plausible', '/ˈplɔːzəbl/', 'adj. 貌似合理的'],
  ['precede', '/prɪˈsiːd/', 'v. 先于'],
  ['predominant', '/prɪˈdɒmɪnənt/', 'adj. 主要的；占优势的'],
  ['preliminary', '/prɪˈlɪmɪnəri/', 'adj. 初步的'],
  ['prevalent', '/ˈprevələnt/', 'adj. 普遍的；流行的'],
  ['profound', '/prəˈfaʊnd/', 'adj. 深刻的；深奥的'],
  ['prolong', '/prəˈlɒŋ/', 'v. 延长'],
  ['propel', '/prəˈpel/', 'v. 推进；驱动'],
  ['quantify', '/ˈkwɒntɪfaɪ/', 'v. 量化'],
  ['rectify', '/ˈrektɪfaɪ/', 'v. 纠正'],
  ['refute', '/rɪˈfjuːt/', 'v. 驳斥'],
  ['relinquish', '/rɪˈlɪŋkwɪʃ/', 'v. 放弃；交出'],
  ['resilient', '/rɪˈzɪliənt/', 'adj. 有韧性的；恢复快的'],
  ['scrutiny', '/ˈskruːtəni/', 'n. 仔细审查'],
  ['simultaneously', '/ˌsɪmlˈteɪniəsli/', 'adv. 同时地'],
  ['skeptical', '/ˈskeptɪkl/', 'adj. 怀疑的'],
  ['spontaneous', '/spɒnˈteɪniəs/', 'adj. 自发的'],
  ['subtle', '/ˈsʌtl/', 'adj. 微妙的'],
  ['tangible', '/ˈtændʒəbl/', 'adj. 有形的；切实的'],
  ['tedious', '/ˈtiːdiəs/', 'adj. 乏味的'],
  ['tentative', '/ˈtentətɪv/', 'adj. 试探性的'],
  ['tranquil', '/ˈtræŋkwɪl/', 'adj. 宁静的'],
  ['unprecedented', '/ʌnˈpresɪdentɪd/', 'adj. 前所未有的'],
  ['versatile', '/ˈvɜːsətaɪl/', 'adj. 多才多艺的；用途广的'],
  ['vigorous', '/ˈvɪɡərəs/', 'adj. 有力的；精力充沛的'],
  ['vulnerable', '/ˈvʌlnərəbl/', 'adj. 脆弱的；易受伤害的'],
];

const PHRASES = [ // ---------- 高频词组 ----------
  ['look forward to', '期待；盼望'],
  ['carry out', '执行；开展'],
  ['lead to', '导致；通向'],
  ['result in', '导致；造成'],
  ['result from', '由…造成；起因于'],
  ['account for', '解释；占比'],
  ['cope with', '应对；处理'],
  ['consist of', '由…组成'],
  ['a range of', '一系列；各种各样的'],
  ['in terms of', '就…而言；在…方面'],
  ['contribute to', '促成；有助于'],
  ['benefit from', '从…中受益'],
  ['rely on', '依赖；依靠'],
  ['focus on', '专注于'],
  ['base on', '基于；以…为基础'],
  ['take part in', '参加；参与'],
  ['take advantage of', '利用'],
  ['make use of', '利用；使用'],
  ['put forward', '提出（建议、观点）'],
  ['come up with', '想出；提出'],
  ['figure out', '弄明白；想清楚'],
  ['point out', '指出'],
  ['turn out', '结果是；证明是'],
  ['bring about', '导致；引起'],
  ['give rise to', '引起；导致'],
  ['keep pace with', '与…同步；跟上'],
  ['be aware of', '意识到'],
  ['be involved in', '参与；卷入'],
  ['be concerned about', '关心；担忧'],
  ['be accustomed to', '习惯于'],
  ['be exposed to', '接触到；暴露于'],
  ['in favour of', '支持；赞成'],
  ['on behalf of', '代表'],
  ['as a result of', '由于；作为…的结果'],
  ['in addition to', '除…之外还'],
  ['apart from', '除…之外'],
  ['regardless of', '不管；不顾'],
  ['in spite of', '尽管'],
  ['by means of', '通过；借助'],
  ['in order to', '为了'],
  ['prior to', '在…之前'],
  ['subject to', '受制于；取决于'],
  ['adapt to', '适应'],
  ['attribute to', '把…归因于'],
  ['commit to', '致力于；承诺'],
  ['conform to', '符合；遵照'],
  ['correspond to', '与…相符'],
  ['devote to', '奉献给；专心于'],
  ['be opposed to', '反对'],
  ['be liable to', '容易…的；可能遭受'],
  ['be bound to', '必定；一定会'],
  ['a variety of', '各种各样的'],
  ['a great deal of', '大量的'],
  ['a large number of', '大量的（可数）'],
  ['the majority of', '大多数'],
  ['on the verge of', '濒临；接近'],
  ['at the expense of', '以…为代价'],
  ['in the long run', '从长远来看'],
  ['in the short term', '短期内'],
  ['for the sake of', '为了…的利益'],
  ['with regard to', '关于'],
  ['in view of', '鉴于；考虑到'],
  ['in light of', '鉴于；根据'],
  ['by comparison', '相比之下'],
  ['in contrast', '相比之下（截然不同）'],
  ['on the contrary', '相反地'],
  ['to some extent', '在某种程度上'],
  ['play a role in', '在…中起作用'],
  ['take measures', '采取措施'],
  ['take into account', '考虑到；顾及'],
  ['draw attention to', '引起对…的注意'],
  ['shed light on', '阐明；使…清楚'],
  ['pose a threat to', '对…构成威胁'],
  ['have an impact on', '对…产生影响'],
  ['raise awareness', '提高意识'],
  ['bridge the gap', '弥合差距'],
  ['strike a balance', '取得平衡'],
  ['reap the benefits', '获得好处'],
  ['suffer from', '遭受；患病'],
  ['recover from', '从…中恢复'],
  ['distinguish between', '区分；辨别'],
  ['participate in', '参加'],
  ['engage in', '从事；参与'],
  ['specialize in', '专攻；专门研究'],
  ['invest in', '投资于'],
  ['excel at', '擅长'],
  ['be proficient in', '精通'],
  ['be capable of', '有能力做'],
  ['be equipped with', '配备有'],
  ['be associated with', '与…相关联'],
  ['be linked to', '与…有联系'],
  ['stem from', '源于'],
  ['derive from', '源自；从…获得'],
  ['arise from', '由…引起'],
  ['date back to', '追溯到'],
  ['be tolerant of', '容忍；宽容'],
  ['be compatible with', '与…兼容'],
  ['be resistant to', '对…有抵抗力'],
];

/* 词库装配：vid 规则 w:单词 / p:词组 */
function build(items, tier, type) {
  return items.map(([w, p, d]) => ({
    vid: (type === 'phrase' ? 'p:' : 'w:') + w.toLowerCase(),
    type, tier, w, p: type === 'phrase' ? '' : p, d,
  }));
}

export const VOCAB_BANK = [
  ...build(T1, 1, 'word'),
  ...build(T2, 2, 'word'),
  ...build(T3, 3, 'word'),
  ...build(PHRASES, 1, 'phrase'),
];

export const TIERS = [
  { id: '1', name: '基础高频', key: '1' },
  { id: '2', name: '核心高频', key: '2' },
  { id: '3', name: '进阶词汇', key: '3' },
  { id: 'p', name: '高频词组', key: 'p' },
];
